# -*- coding: utf-8 -*-
"""ckd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ThrTuz_T38MadqzAPuNEMU7Vn4P14xB1
"""

data=pd.read_csv("kidney_disease.csv")

import pandas as pd
import numpy as np
from collections import Counter as c
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
import pickle

data.head()

data.tail()

data.head(10)

data.columns

data.columns=[ 'id','age','blood_pressure','specific_gravity','albumin',
              'sugar','red_blood_cells','pus_cell','pus_cell_clumps','bacteria',
              'blood glucose random','blood_urea','serum_creatinine','sodium','potassium',
              'hemoglobin','packed_cell_volume','white_blood_cell_count','red_blood_cell_count',
              'hypertension','diabetesemellitus','coronary_artery_disease',' appetite',
              'pedal_edema','anemia','class']
data.columns

data.describe()



data.info()

data.isnull().any()

data['blood glucose random'].fillna(data['blood glucose random'].mean(),inplace=True
data['blood_pressure'].fillna(data['blood_pressure'].mean(),inplace=True)
data['blood_urea'].fillna(data['blood_urea'].mean(),inplace=True)
data['hemoglobin'].fillna(data['hemoglobin'].mean(),inplace=True)
data['packed_cell_volume'].fillna(data['packed_cell_volume'].mean(),inplace=True)
data['potassium'].fillna(data['potassium'].mean(),inplace=True)
data['red_blood_cell_count'].fillna(data['red_blood_cell_count'].mean,inplace=True)
data['serum_creatinine'].fillna(data['serum_creatinine'].mean,inplace=True)
data['sodium'].fillna(data['sodium'].mean,inplace=True)
data['white_blood_cell_count'].fillna(data['white_blood_cell_count'].mean,inplace=True)

data['age'].fillna(data['age'].mode()[0],inplace=True)
data['id'].fillna(data['id'].mode()[0],inplace=True)
data['hypertension'].fillna(data['hypertension'].mode()[0],inplace=True)
data['pus_cell_clumps'].fillna(data['pus_cell_clumps'].mode()[0],inplace=True)
data['appetite'].fillna(data['appetite'].mode()[0],inplace=True)
data['albumin'].fillna(data['albumin'].mode()[0],inplace=True)
data['pus_cell'].fillna(data['pus_cell'].mode()[0],inplace= True)
data['red_blood_cells'].fillna(data['red_blood_cells'].mode()[0],inplace=True)
data['coronary_artery_disease'].fillna(data['coronary_artery_disease'].mode()[0],inplace=True)
data['bacteria'].fillna(data['bacteria'].mode()[0],inplace=True)
data['anemia'].fillna(data['anemia'].mode()[0],inplace=True)
data['sugar'].fillna(data['sugar'].mode()[0],inplace=True)
data['diabetesemellitus'].fillna(data['diabetesemellitus'].mode()[0],inplace=True)
data['pedal_edama'].fillna(data['pedal_edama'].mode()[0],inplace=True)
data['specific_gravity'].fillna(data['specific_gravity'].mode()[0],inplace=True)
data['class'].fillna(data['class'].mode()[0],inplace=True)



from google.colab import files
uploaded=files.upload()

for i in catcols:
    print("columns:",i)
    print(c(data[i]))
    print('*'*120+'\n')

catcols=set(data.dtypes[data.dtypes=='0'].index.values)
print(catcols)

contcols.add('red_blood_cell_count')
contcols.add('packed_cell_volume')
contcols.add('white_blood_cell_count')
print(contcols)

catcols=['anemia','pedal_edema','appetite','bacteria','class','coronary_artery_disease','diabetesmellitus',
         'hypertension','pus_cell','pus_cell_clumps','red_blood_cells']

from sklearn.preprocessing import LabelEncoder
for i in catcols:
   print("LABEL ENCODING OF:",i)
   LEi=LabelEncoder()
   print(c(data[i]))
   data[i]=LEi.fit_transform(data[i])
   print(c(data[i]))
   print("*"*100)

contcols=set(data.dtypes[data.dtypes!='0'].index.values)
print(contcols)

